SELECT EMP.FIRST_NAME "NOMBRE",
       EMP.LAST_NAME "APELLIDO",
       TO_CHAR(EMP.SALARY, '$999G999G999') "SUELDO",
       EMP.DEPARTMENT_ID "CODIGO DEPTO",
       DEP.DEPARTMENT_NAME "NOMBRE DEPARTAMENTO"
FROM EMPLOYEES EMP
    JOIN DEPARTMENTS DEP ON EMP.DEPARTMENT_ID =
                            DEP.DEPARTMENT_ID;
                            
SELECT DEP.DEPARTMENT_NAME "NOMBRE DEL DEPARTAMENTO",
       DEP.LOCATION_ID "ID LOCACION",
       LOC.CITY "CIUDAD",
       LOC.STREET_ADDRESS "DIRECCION",
       CON.COUNTRY_NAME "REGION"
FROM DEPARTMENTS DEP
    JOIN LOCATIONS LOC ON DEP.LOCATION_ID = 
                          LOC.LOCATION_ID
    JOIN COUNTRIES CON ON LOC.LOCATION_ID =
                          COUNTRY_ID;